#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUT = ROOT / "build" / "DCH-Shure-MXCWAPT.qplug"

MODULES = [
    "commands",
    "protocol",
    "state",
    "diagnostics",
    "properties",
    "controls",
    "layout",
    "runtime",
]


def module_name(name: str) -> str:
    return f"src.modules.{name}"


def main() -> None:
    entry = (SRC / "DCH-Shure-MXCWAPT.qplug.lua").read_text()
    header = re.match(r"\APluginInfo = \{.*?\n\}\n", entry, re.DOTALL)
    if header is None:
        raise ValueError("Plugin entry must start with PluginInfo")
    chunks = [
        header.group(0),
        "-- Generated by scripts/build_qplug.py. Edit files in src/ instead.\n",
        "local module_loaders, module_values = {}, {}\n",
        "local function require(name)\n",
        "  if module_values[name] ~= nil then return module_values[name] end\n",
        "  local loader = assert(module_loaders[name], 'Missing bundled module: ' .. name)\n",
        "  local value = loader()\n",
        "  module_values[name] = value\n",
        "  return value\n",
        "end\n",
    ]
    for mod in MODULES:
        path = SRC / "modules" / f"{mod}.lua"
        chunks.append(f"\nmodule_loaders[{module_name(mod)!r}] = function()\n")
        chunks.append(path.read_text())
        chunks.append("\nend\n")
    chunks.append("\n")
    chunks.append(entry[header.end():])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(chunks))
    print(OUT)


if __name__ == "__main__":
    main()
